### ISSUE TITLE
Can we write this in C ?

### ISSUE THREAD

**Issue by n1tram1** [ks0n/ubsh#1]
C is clearly a superior language to other languages people could propose.
This python example shows this clearly:
```python
languages = ["C", "Rust"]
languages.sort()
print(languages[0])
```

**Comment by n1tram1** [comment]
Oh I didn't read the description of the project properly, I didn't get this wasn't posix. I'll just write another posix shell.

**Comment by CohenArthur** [comment]
This is going to be written in C, no worries. Rust is not ready yet for a project of this magnitude

**Comment by CohenArthur** [comment]
Also the shell relies on Undefined Behavior (it's in the name), and the craby language does not have undefined behavior, therefore it is unfit for `ubsh`

**Comment by n1tram1** [comment]
Are we sure we want this to be not POSIX ? We might as well write a computer virus (which is already happening considering the BSD3 license).

**Comment by Skallwar** [comment]
> Are we sure we want this to be not POSIX ?

I kind of agree with this. Maybe we don't need here-documents an some other useless stuff but POSIX is great (and make people use your shell). If we want another syntax we could just make an option later on but at least it will be POSIX

> (which is already happening considering the BSD3 license)

So true

**Comment by CohenArthur** [comment]
I am personally not against it but we need to decide what to remove from the POSIX spec. I agree that heredocs should not have a place here. I'm also against string expansion as it is usually done in a POSIX shell

**Comment by Skallwar** [comment]
> I'm also against string expansion as it is usually done in a POSIX shell

So no variables?

**Comment by CohenArthur** [comment]
No, what I mean is that `z=$(($z+3))` is not a good way to represent arithmetic expansion and that  `${stringZ%%b*c}` isn't really the clearest way to perform substitution. And we should change that

**Comment by Skallwar** [comment]
So we keep basic extensions?

**Comment by CohenArthur** [comment]
What basic extensions do you have in mind?

**Comment by Skallwar** [comment]
> What basic extensions do you have in mind?

expansions sorry

Variable, environment variables. There might be others but I don't remember well :sweat_smile:
