### ISSUE TITLE
Unit test tool

### ISSUE THREAD

**Issue by Skallwar** [ks0n/ubsh#17]
What unit test tool to use?
 - [Criterion](https://github.com/Snaipe/Criterion/)?
 - [NovaProva](https://github.com/novaprova/novaprova)?

**Comment by CohenArthur** [comment]
What about libcmocka? It's simple and lightweight, and easy to integrate with meson

**Comment by Skallwar** [comment]
> What about libcmocka?

I not a fan of lib without dynamic test discovery

**Comment by Skallwar** [comment]
I've found [ibcester](https://exoticlibraries.github.io/libcester/) which looks great also

**Comment by Skallwar** [comment]
[ctest](https://github.com/bvdberg/ctest)

**Comment by CohenArthur** [comment]
@08A @n1tram1 do you guys have any preference? I'm fine with all of these
